version: '3.9'
services:
db:
image: postgres:16
environment:
POSTGRES_PASSWORD: postgres
POSTGRES_DB: dsm
ports: ["5432:5432"]
volumes:
- dbdata:/var/lib/postgresql/data


ipfs:
image: ipfs/kubo:latest
ports:
- "4001:4001/tcp"
- "4001:4001/udp"
- "5001:5001"
- "8080:8080"
volumes:
- ipfs_staging:/export
- ipfs_data:/data/ipfs


volumes:
dbdata:
ipfs_staging:
ipfs_data:
